### ISSUE TITLE
Add "Find selection"

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#103]
There's another feature I constantly use with Koder, that'd love to see in Genio as well:
Select a portion of text - say **fName** -  and invoke "`Search | find selection    ALT+H`" and you'll jump to (and select) the next **fName**.
That way you can quickly cycle to all hits without invoking (and btw keeping the search term in) the Find window.

**Comment by nexus6-haiku** [comment]
Alt-F shows the find panel with the selected text pre-filled for you.

**Comment by humdingerb** [comment]
As does Koder. ALT+H is just a quicker way, avoids popping up a window that you may have to move so it doesn't obscure text, and keeps the last used 'real' search term in the Find window.
Just a suggestion, ofc.

**Comment by nexus6-haiku** [comment]
I see what you mean, it makes sense then.

**Comment by humdingerb** [comment]
I changed my mind. After having used Genio for a bit, I think I can very well live without this. :)
Doing ALT+F with the current selection is more convenient because you can jump to the next and previous finds. Or use "Find in project" to get a list in the output pane's "Search results" you can conveniently jump via double-click. The previous search term is quickly set again from the "Find" pop-up history.

**Comment by jackburton79** [comment]
I'm glad we've convinced you, and without any effort I might add (other than keep developing Genio) :-)
What do you think about this ticket? Shall se close It or keep it open? What do you think
@nexus6-haiku @Freaxed @humdingerb ?

**Comment by humdingerb** [comment]
Feel free to close. Hard enough to find a yet not used shortcut for something actually important. 😃
