### ISSUE TITLE
project pane -> rightclick on file -> open does not work (always)

### ISSUE THREAD

**Issue by thaflo** [Genio-The-Haiku-IDE/Genio#114]
tried it a few times to open Makefiles and .cpp
does not open always, like with double click
(I work under VirtualBox) - if it works on bare metal always, it could be a thing of the VM

**Comment by jackburton79** [comment]
Happens here too, sometimes

**Comment by jackburton79** [comment]
Actually, here it was a regression in my branch.
Are you using the beta 1 release ?
I think this bug is fixed in the main branch

**Comment by jackburton79** [comment]
Does this still happen ?
