### ISSUE TITLE
Remove trailing spaces on lines when saving.

### ISSUE THREAD

**Issue by tclaus** [Genio-The-Haiku-IDE/Genio#12]
It happens easily and wastes git's diff.

These should be removed on every save.

**Comment by nexus6-haiku** [comment]
Could you please elaborate?

**Comment by tclaus** [comment]
As a developer, every change I make, I make it with a purpose. Code -> Test,make -> Code. 
Currently I have a terminal open to run make regular. Or I click the male button. But this requires that the file is saved. 

Also, if at some point in future clang-tidy or clan-check runs, the file needs to be saved anyway. 

Currently I need to save manually very often. 

The worry, to save an unwanted change can be eliminated by using git.

**Comment by tclaus** [comment]
I already tried to write some code for this, but it fails in the (new) Gtests. Maybe I can hand in a draft PR on this?

**Comment by nexus6-haiku** [comment]
Just to clarify. "Trailing" here means at the end of the line, doesn't it?

**Comment by tclaus** [comment]
Yes, the  line endings, or even empty lines. A space is literally invisible, but pollutes a diff in pull requests for example.

**Comment by Freaxed** [comment]
I use genio as the main editor for developin genio itself.. and never experienced this issue.. can it be related to line endings format? (unix/windows style)? Have you tryed to show the line endings in the editor to visual undestanding what's going on?

**Comment by jackburton79** [comment]
Working on this in the feature/buildonsave branch
