### ISSUE TITLE
Crash while typing

### ISSUE THREAD

**Issue by jackburton79** [Genio-The-Haiku-IDE/Genio#122]
I was typing in a Genio window, and got this crash
[WhileTyping-Genio-46270-debug-12-10-2023-14-59-35.report.zip](https://github.com/Genio-The-Haiku-IDE/Genio/files/12884006/WhileTyping-Genio-46270-debug-12-10-2023-14-59-35.report.zip)

**Comment by Freaxed** [comment]
This should be fixed by https://github.com/Genio-The-Haiku-IDE/Genio/commit/f5c7f25f95f0b62c0e06f9af428c4aea77cec21e

**Comment by jackburton79** [comment]
Will try. Thanks!
