### ISSUE TITLE
Crash on Find in project

### ISSUE THREAD

**Issue by nexus6-haiku** [Genio-The-Haiku-IDE/Genio#132]
it's replicable only on one specific project ([TrackGit]( https://github.com/HaikuArchives/TrackGit)) by searching "cred_acquire_cb".

[Genio_debug-3790-debug-29-10-2023-14-09-13.report.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/13198276/Genio_debug-3790-debug-29-10-2023-14-09-13.report.txt)

**Comment by nexus6-haiku** [comment]
UPDATE: it crashes with whatever term on the very same project

**Comment by Freaxed** [comment]
Fixed with https://github.com/Genio-The-Haiku-IDE/Genio/commit/85393e10929e0b2926906f4871ca121aaee0ec6b
