### ISSUE TITLE
Double-click to expand folders

### ISSUE THREAD

**Issue by dsizzle** [Genio-The-Haiku-IDE/Genio#144]
I'd love the ability to double-click to expand/collapse folders rather than just clicking the `>` symbol.

**Comment by jackburton79** [comment]
Although this isn't usually how BOutlineListViews work in Haiku, I guess we could try to implement this. After all, the ProjectFolderbrowser works more or less like a file system browser.
What do you think, @nexus6-haiku @Freaxed ?
