### ISSUE TITLE
Norwegian translation completed

### ISSUE THREAD

**Issue by dospuntos** [Genio-The-Haiku-IDE/Genio#145]
Just  a note that the Norwegian translation on [Polyglot](https://i18n.kacperkasper.pl/projects/46) is complete. I will use Genio in Norwegian to see if I pick up any mistakes, but all available strings have been translated.

Some strings are not available to translate in Polyglot, but I assume they are part of work in progress.

![image](https://github.com/Genio-The-Haiku-IDE/Genio/assets/12958546/8efaa30f-bf76-45d3-8274-005cafdbe174)

**Comment by jackburton79** [comment]
We'll update the catkeys real soon
