### ISSUE TITLE
Some colours don't follow the system scheme and don't match with a dark theme set in Haiku

### ISSUE THREAD

**Issue by nexus6-haiku** [Genio-The-Haiku-IDE/Genio#151]
Specifically, the Build and Console I/O logs and the text in the StatusView are always black

**Comment by nexus6-haiku** [comment]
+ in the editor tabs: the close icon "x" and the down facing arrow of the right-hand side menu

**Comment by Freaxed** [comment]
Can you please check with one of the latest version? I did a fix for
consoleIo to follow the theme

Il giorno lun 13 nov 2023 alle 10:27 Davide Alfano ***@***.***>
ha scritto:

**Comment by nexus6-haiku** [comment]
I confirm that Build and Console I/O logs are ok now but we should probably change the background colour to match Search Results and Problems.

**Comment by nexus6-haiku** [comment]
The issue with BuildLog and Console I/O is with the dark theme and not an issue in Genio

**Comment by jackburton79** [comment]
So, can this be closed ?

**Comment by nexus6-haiku** [comment]
This issue tracks also other parts of Genio which don't adapt well to the dark theme like the x on the right-hand side of a tab.
I would keep it open.

**Comment by jackburton79** [comment]
Fixed tab close buttons.
@nexus6-haiku what is missing to close this ?

**Comment by jackburton79** [comment]
Retested. Fixed.
