### ISSUE TITLE
Rename "Output pane" to "Info pane"

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#158]
Since there are already "Search results" and in future maybe other stuff as well.

**Comment by jackburton79** [comment]
Do you think it's still valid ?

**Comment by humdingerb** [comment]
I suppose it's still valid, but never was a "biggie", of course.
While "Output pane" is technically correct - the pane shows any 'output' the Genio app produces - "Info pane" is more general. At least in the English locale, "Output pane" and "Outline pane" look quite similar, but that's of course just a tiny detail of this small issue...
Do as you think best. :)
