### ISSUE TITLE
Switching projects

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#162]
The context menu with "Set active" on a project in the left sidebar is a bit hidden, I think.
How about adding a "Select project >" with a submenu listing all the currently open projects? Disable, if there's just one project open.
The Genio window title could also add the currently active project name.

**Comment by jackburton79** [comment]
I think we could definitely improve the situation in some way. Thanks for the suggestions.

**Comment by jackburton79** [comment]
Added a Set active submenu in the project menu.
