### ISSUE TITLE
Crash when "Switch to branch" menu is about to open

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#163]
Move your mouse over the "Switch to branch" menu, and Genio crashes.

[Genio-5498-debug-21-11-2023-14-08-58.report.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/13427195/Genio-5498-debug-21-11-2023-14-08-58.report.txt)

**Comment by nexus6-haiku** [comment]
is it happening on a project that does not have a git repository?

**Comment by humdingerb** [comment]
No. I duplicated a project folder and removed the '.git' folder contained within. Opening it in Genio as new project, the "Switch to branch" menu doesn't lead to a crash.

**Comment by nexus6-haiku** [comment]
Can you reproduce it by doing a verbatim copy of that folder? I.e. without removing the .git folder.
Does it happen on other projects?

The log does not say much except that GitRepository ctor seems to crash without even getting the list of the branches.

Would it be possible to get a copy of the whole folder of your project?

**Comment by humdingerb** [comment]
It may be a user error... :)

My project usually have a "src" subfolder with a ll the code files, plus a Makefile.
I (mis?)understand that Genio has trouble building when the Makefile isn't in the top folder. I therefore did not open the project with its  top folder "quicklaunch", but the "src" subfolder. Here the "make" works, but I get the crash on "Switch to branch".
If however I open the project with its topfolder, there's no crash.
The "git" folder is in the topfolder, too...

Here's a zip of the folder, if you still need it.
[quicklaunch copy.zip](https://github.com/Genio-The-Haiku-IDE/Genio/files/13428470/quicklaunch.copy.zip)

**Comment by humdingerb** [comment]
Oh, and stupid me could just have use "make -C src" in the project settings to make builds work from the top folder... :)

**Comment by jackburton79** [comment]
I can reproduce by opening the "haikuports" repository as a project, opening a subdirectory instead of the main directory.
