### ISSUE TITLE
"Debug project" feezes Genio window while Debugger is running

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#167]
see title

**Comment by jackburton79** [comment]
This could be because we launch debugger with "system()" ?

It seems we used BRoster::Launch() before, but there were issues and @nexus6-haiku changed it in commit f532e1dd1523e848007b8e5c79ab1bffda7a6d21 .
Can you comment on this, @nexus6-haiku ?

**Comment by nexus6-haiku** [comment]
Well the thing is simple, it didn't work via BRoster::Launch() as the Debugger does not seem to receive the provided parameter(s).
It was a long time ago and never came back on it, to be honest.

**Comment by jackburton79** [comment]
I had a look with the old code (which would fix this issue): it seems the parameters get garbled when they get to Debugger. I opened ticket
https://dev.haiku-os.org/ticket/18683 in haiku.
