### ISSUE TITLE
Show "Output pane" when doing a "Find in project"

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#168]
As "Find in project" shows its results in the output pane, doing "Find in project"  should force-show the output pane. 
Currently, if the output pane was hidden, it stays hidden, forcing the user to manually show it.

**Comment by Freaxed** [comment]
Fixed with https://github.com/Genio-The-Haiku-IDE/Genio/commit/f662210211259043a3afc853a6d9226ed57146b8
