### ISSUE TITLE
Toolbar glitch on click and move

### ISSUE THREAD

**Issue by jackburton79** [Genio-The-Haiku-IDE/Genio#173]
Click on a two-state toolbar item (for example, the first button on the left). Keep the mouse button clicked while you move the cursor outside the button, then release the mouse button.
The toolbar button will change state (pressed -> unpressed, or vice-versa), but the associated action will not fire.

**Comment by jackburton79** [comment]
Interestingly Koder, while using the same Toolbar api, doesn't suffer from this problem.

**Comment by Freaxed** [comment]
Fixed in commit bd49ed125e53e7a9ca1be0ab47c7ccd6b89ba5e1 (on feature/source-control branch)
