### ISSUE TITLE
Cancelling save-changes-alert doesn't cancel

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#175]
If you made changes to a file and close the file, an alert pops up to "cancel", "don't save" or "save" the changes.
If you "cancel" the file is closed without saving! So, it "don't save" instead of "cancel" the closing of the file.
Oops. :)

**Comment by Freaxed** [comment]
Thank you for finding this! fixed in 9529c8122de7d49a850b2551846c776a95a90247
