### ISSUE TITLE
Double-click on error in build log to jump into source does't work in certain cases

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#177]
I think I remember this already working before, but I may just imagine this...
Also, I can't totally parse #11, this may be a duplicate.

**Comment by jackburton79** [comment]
Not sure about this: if I click on the error it definitely jumps into the source file where the build error is.
Isn't it working for you?

**Comment by humdingerb** [comment]
It definitely did not work back then. I remember having to manually find the file and line. Very annoying...  :)
It works now, underlining and all. Thanks!.

**Comment by humdingerb** [comment]
Hmm... now it doesn't work any more again...
I tried with the v2 version from HaikuDepot and building the current "main" branch. I tried removing the Genio settings folder. Still no build error jumping. Any ideas?

**Comment by nexus6-haiku** [comment]
Does the project path contain a space?

**Comment by humdingerb** [comment]
Nope, it's `/Source/KeyCursor`. No spaces in file names either.

**Comment by Freaxed** [comment]
If it still happen, please increase the log level to Trace set the destination to syslog/BeDC to try to collect some information.
Thanks!

**Comment by humdingerb** [comment]
It works with other projects, but for some reason fails for "KeyCursor".
Attached the Trace syslog, and the zipped up project folder. Maybe it works for you...(?)

For the trace, I just removed a semicolon. A build failure is shown with the exact line it occurs, but I cannot double-click it...

[build-syslog.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/13804229/build-syslog.txt)
[KeyCursor.zip](https://github.com/Genio-The-Haiku-IDE/Genio/files/13804231/KeyCursor.zip)

BTW, is "BeDC" this thing: [BDirectConnect](https://depot.haiku-os.org/#!/pkg/bdirectconnect/haikuports/haikuports_x86_64/0/5/0/git/2/x86_64?bcguid=bc200-YPCD#%2F%3Fbcguid=bc1-NSYT&arch=x86_gcc2&viewcrttyp=FEATURED&repos=haikuports) ?
How do you use it?

**Comment by nexus6-haiku** [comment]
The only suspect line is

USER: Genio: {T} Can't find path /Source/KeyCursor/preflet/KeyCursor

Is there a file, folder or symlink with that name? I can't spot it in the zip file (I'm checking from my iPhone so not the best tool to look into this).

BeDC stands for Developer Console, is an old tool from the BeOS days that PulkoMandy has revived for Haiku 64bit.

**Comment by humdingerb** [comment]
That would be the built preflet binary.

I didn't find BeDC in HaikuDepot. ..

**Comment by Freaxed** [comment]
Ok I can reproduce it but cleary we cannot do much here.
The same 'bug' can be seen in Terminal by compiling, then pressing  the B_CONTROL_KEY and move the mouse cursor over KeyCursorFilter.cpp.. no way to select and to open it.
This is due the fact that the makefile doesn't express file location relative to the root folder and Genio is not able to locate the it.
When the mouse moves over the text and algo is extracting the possible 'path' and checking if it does exist as an absolute or relative path. Maybe we could also search the list of all the project's files but it could be a bit heavy to be performed on mouse move.

**Comment by nexus6-haiku** [comment]
Maybe we can just check whether it's not an absolute path and assume the root is the working directory (this should already be the project's folder, I think)?

**Comment by humdingerb** [comment]
The complication here is that there are two Makefiles in two subfolders of the project and one Makefile in the project folder that calls those other Makefiles...

**Comment by Freaxed** [comment]
I don't think we can understand the cwd of a separate running process.. moreover is can change while running and after stopping

**Comment by jackburton79** [comment]
Let's close this for now, as there is nothing we can do, unfortunately.

**Comment by nexus6-haiku** [comment]
This should be fixed by #455
