### ISSUE TITLE
Open new tab to the right of the active tab

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#181]
Currently new files are opened in a tab at the far right of the tab bar.
Sometimes you just want to have a quick look at another file, may to just quickly copy some lines, and immediately close the file again. Unfortunately, you're now at the end of the tab bar and - if you have many files open - need to scroll back to the left in the tab bar and find the file you were at before.

If the new file would not open at the right end of the tab bar, but to the right of the currently active tab, you would automatically end up at the original tab when you close the newly opened tab.

**Comment by jackburton79** [comment]
It makes much sense.
I haven't looked at that code to see how hard is to change this behaviour but I agree with this change

**Comment by Freaxed** [comment]
I also agree.. maybe is a bit tricky to define the behaviour in case of
multiple file opening (like at startup), but we can sort it out

Il giorno mer 6 dic 2023 alle 20:34 Stefano Ceccherini <
***@***.***> ha scritto:
