### ISSUE TITLE
Crash when opening and closing a project 

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#186]
Seems to crash only if the projects list was empt before opening a project (so it's the first project) or when closing the last project in the list (so it's empty afterward).

[Genio-9446-debug-08-12-2023-18-26-22.report.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/13619730/Genio-9446-debug-08-12-2023-18-26-22.report.txt)

**Comment by jackburton79** [comment]
Seems like the fSelectedProject in sourceControlPanel can become invalid when projects are removed, because it's never set to null
