### ISSUE TITLE
Active project isnt bolded any more in projects pane

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#188]
Must've happened with one of the last commits.

**Comment by jackburton79** [comment]
Yes, I had broken It, but I think I've fixed It here: https://github.com/Genio-The-Haiku-IDE/Genio/commit/8a0dde2c8d1b466e39aaff07f25dd6e02ae1ff58

**Comment by humdingerb** [comment]
Indeed. Sorry about that, I'm not used to you guys' coding velocity... :)
I'll make sure to check out and build from the latest changes in the future before creating a ticket.

**Comment by jackburton79** [comment]
> Indeed. Sorry about that, I'm not used to you guys' coding velocity... :)
> I'll make sure to check out and build from the latest changes in the future before creating a ticket.

I can promise, at least, I will try to avoid breaking so many things in a row, next time 😅

**Comment by jackburton79** [comment]
Thanks for your help in finding bugs and for your suggestions, by the way

**Comment by humdingerb** [comment]
My pleasure. :)
BTW, if you plan to do a Genio Xmas release, you may want to do any GUI string additions/changes that are ready now, update the catkeys at Polyglot and ask for translations at https://discuss.haiku-os.org/t/translations-needed-for-upcoming-3rd-party-app-release
Even if you have to add/update some strings after the announcement, it gives the translators a head start to get the bulk of strings finished for the release.

**Comment by jackburton79** [comment]
> My pleasure. :)
> BTW, if you plan to do a Genio Xmas release, you may want to do any GUI string additions/changes that are ready now, update the catkeys at Polyglot and ask for translations at https://discuss.haiku-os.org/t/translations-needed-for-upcoming-3rd-party-app-release
> Even if you have to add/update some strings after the announcement, it gives the translators a head start to get the bulk of strings finished for the release.

Yes, of course. I think we're mostly done with changes, except for minor things.
