### ISSUE TITLE
Write a user guide

### ISSUE THREAD

**Issue by jackburton79** [Genio-The-Haiku-IDE/Genio#191]
Write an user guide (with screenshots) which documents the existing functionalities (some of which are a bit hidden)

**Comment by jackburton79** [comment]
Done by @humdingerb .
Great work! Not complete but a good start

**Comment by humdingerb** [comment]
I continue adding to the documentation.
Should we just re-open this issue, so we don't get our wires crossed and work on it in parallel?

**Comment by jackburton79** [comment]
> I continue adding to the documentation. Should we just re-open this issue, so we don't get our wires crossed and work on it in parallel?

Let's reopen it.
Can I assign the issue to you?

**Comment by humdingerb** [comment]
By all means. :)

**Comment by jackburton79** [comment]
Shall we close this ?

**Comment by humdingerb** [comment]
Yes. I'll keep an eye out on changes to Genio that impact the user guide. Though I may miss something... Feel free to create issues when you see stuff missing and assign to me.

**Comment by jackburton79** [comment]
Thanks!
