### ISSUE TITLE
AboutWindow: Changelog not translated. Remove?

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#192]
The changelog will be quite substantial with time, if you can keep up even a fraction of the current pace... :)

It'll become quite long to scroll through, and quite some work for the translators if it's made translatable (which it should be as all the rest of the app is translated).
Maybe it's enough to put the English version into HaikuDepot's changelog which can be viewed from the HaikuDepot app before the user installs it?

**Comment by jackburton79** [comment]
The way the Changelog is done now isn't translatable.
We might want to change that in the future, or remove it. We haven't decided yet.
For now, I guess we can keep it as is, and load the changelog into HaikuDepot, when we release the next version.

**Comment by humdingerb** [comment]
+1
