### ISSUE TITLE
Settings: Sections in outline view at the left untranslatable

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#193]
The outline listview at the left ("General, Startup, Editor...") isn't yet translatable.

**Comment by jackburton79** [comment]
This can be done, but the strings won't change in real time: you'd have to close and reopen Genio to see the changes

**Comment by humdingerb** [comment]
Hmm... isn't that the usual behaviour? If you change the language in the Locale prefs, you have to restart apps for them to show the new translation.
I mean those strings aren't collected in the catkeys yet.

**Comment by jackburton79** [comment]
Sorry, I thought it was live, for some reason.
Anyway, it's done now!

**Comment by humdingerb** [comment]
It would be cool, no doubt. :)
