### ISSUE TITLE
Add key-combos to switch files

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#198]
The previous/next file arrow icons and the close icon at the right of the toolbar aren't that useful.

Their functions can be reached more easily/intuitively: click or mouse wheel over the tabs, click their close button or ALT+W.
It would be more useful to offer a key-combo to switch through the open files, e.g. CTRL+CursorLeft/Right. That way you could quickly move through the open files without having to reach for the mouse.

For discoverability, it could be added to the "View" menu:
"Go to previous file - CTRL+CursorLeft"
"Go to next file - CTRL+CursorRight"

**Comment by jackburton79** [comment]
Aren't those shortcuts used by textcontrols nowadays?

**Comment by humdingerb** [comment]
Word-wise jumping in textcontrols is done with ALT+cursor (= B_COMMAND_KEY). That one is used in Genio's editor view as well.
CTRL+cursor currently inserts some control character in the editor view. If instead we'd switch tabs, we'll have a winner.

**Comment by jackburton79** [comment]
Now that I see, there is already a shortcut to switch between tabs: option key + left / right arrow.
Does it make sense to switch to CTRL ? @Freaxed @nexus6-haiku what do you think ?

**Comment by jackburton79** [comment]
Ok, let's change then

**Comment by jackburton79** [comment]
Currently ALT+N is used to switch to the Nth tab (as in Webpositive). Would have been nicer to have some consistency: now you'd have ALT+N to switch to the Nth tab and CTRL+LEFT/RIGHT to switch between tabs. Too bad. I guess we'd have to rethink shortcuts system-wide in Haiku
