### ISSUE TITLE
Build action should save all files open in the editor

### ISSUE THREAD

**Issue by nexus6-haiku** [Genio-The-Haiku-IDE/Genio#2]
Upon building a project, Genio should save all files opened in the Editor belonging to that project

**Comment by Freaxed** [comment]
Maybe a popup question should appear: “Save all docs?”: “Yes”, “No”,
“Always”, “Cancel”


Il giorno mar 24 gen 2023 alle 16:58 Davide Alfano ***@***.***>
ha scritto:

**Comment by tclaus** [comment]
There is no reason to ask. IMHO a file should be saved after a short on every change. Thats what a developer needs. 
The edit-save-test/build-loop is so windows/90'.

**Comment by jackburton79** [comment]
Working on this in the feature/buildonsave branch
