### ISSUE TITLE
Accept dropped folders in Projects pane

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#201]
It would be nice not to have to use the file dialog of the "Open project..." menu if I already have the Tracker window of the project open. A quick drag'n'drop of the folder into the projects pane could add the project.

(Not for v2.0, of course. :)

**Comment by jackburton79** [comment]
Needs to be thought through. One could expect that dropping a folder into that area would copy the folder inside the project.
Maybe there should be a special area where dropping a folder would open a project

**Comment by humdingerb** [comment]
I don't think people will be confused about this. It seems intuitive that instead of navigating to and selecting a folder in Projects's "Open project...", you drop a folder and it gets added as new project. Files aren't accepted, and folders always end up as new project, never added as subfolder of an existing one. Users will get it. :)
Plus, when the Projects tab is empty, there could be a text:

_Drop folders to add
as new projects._

**Comment by jackburton79** [comment]
It's done in main branch.
I haven't add "drop folders to add a new project" yet, though, as it will require some more work

**Comment by humdingerb** [comment]
Works!
Two things: Should the user be able to drop several folders at once that will each get added as new projects? I think so.
And should the newly dropped project automatically get expanded and made active? I think that's what you normally want. (In case of several dropped new projects, activate the last (or first, doesn't matter...).

**Comment by jackburton79** [comment]
Yeah I think it can be done. If the user drops file and folders at the same time, what would you expect it to do?

**Comment by humdingerb** [comment]
Ignore files. The Project pane only accepts folders which will become new projects.

**Comment by jackburton79** [comment]
That could work, I guess. Needs some rework of the drop mechanism, though : currently it's the window who handles the drop. In fact, you can drop file/folders on any zone in the window and the result is the same.

**Comment by jackburton79** [comment]
Yes, that was the original idea. I wanted something similar for the outline (when in "creating outline" phase) but never managed to get it right. As soon as I add a cardlayout the layout breaks in a weird way

**Comment by humdingerb** [comment]
Good to know I'm not alone struggling with this...:)
