### ISSUE TITLE
BNotifications for source control actions not needed

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#206]
The commands to create/rename/delete etc. branches in the source control pane cause BNotifications. That's more annoying than helpful IMO. All those commands are pretty instantaneous and the result is immediately visible in the outline list view.

**Comment by nexus6-haiku** [comment]
Could you be more specific on the notifications you deem unnecessary?
It may apply to delete, rename and create maybe but not others?

**Comment by humdingerb** [comment]
Yes, create/rename/delete branches are the ones in no need of a BNotification to signal success. They all have readily visible consequece: a newly created branch appears, a renamed branch shows its new name, a deleted branch disappears.

The other actions in the source control tab do need some sort of success notification. You cannot easily see if a "stash" action was successful. "fetch" probably neither, but I didn't try because of missing ssh-access.

See also #234 I just created.

**Comment by jackburton79** [comment]
Fix applied both in main and in the release/2 branch
