### ISSUE TITLE
Choosing a volume in Project's "Open recent" menu freezes Genio

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#207]
For some reason, I have two of my volumes, "HiQ-Data" and "Source", in the list of recent projects. I tried removing the Genio settings folder competely, but they are still there. I'm not sure how they got in there...

Choosing one of those volumes from the menu peg a CPU and freezes the Genio window, see the attached (probably unhelpful) report.

[Genio_debug-3768-debug-16-12-2023-16-15-01.report.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/13693138/Genio_debug-3768-debug-16-12-2023-16-15-01.report.txt)

**Comment by jackburton79** [comment]
The list Is built and housekeeped by BRoster's recent documents functionality.
I think I had a similar problem with Genio once or twice by going to the desktop with the open project filepanel

**Comment by jackburton79** [comment]
> Choosing one of those volumes from the menu peg a CPU and freezes the Genio window, see the attached (probably unhelpful) report.
> 

I suspect Genio tries to scan the whole volume and load all the files into the project. Since currently Genio does this with a synchronous operation, the window looks frozen

**Comment by humdingerb** [comment]
That appears likely, I see my drive LED thrashing.
Not sure how the whole volume got in there, maybe I misclicked once. Anyway, maybe another mechanism than remembering any folder would be better.

You could have the .genio file have its own MIME type, index it and have a query for that. From the result, pick the last 10 or 20. Make sure to touch a project's .genio file when closing it.
Or simply save a list of last opened projects in the settings, I guess... Though the query would transparently deal with removed project folders and un/mounted volumes with projects on them. Won't work with non-BFS storage though.
Decisions, desicions... all yours. :)

**Comment by jackburton79** [comment]
> That appears likely, I see my drive LED thrashing.
> Not sure how the whole volume got in there, maybe I misclicked once. Anyway, maybe another mechanism than remembering any folder would be better.
> 
> You could have the .genio file have its own MIME type, index it and have a query for that. From the result, pick the last 10 or 20. Make sure to touch a project's .genio file when closing it.
> Or simply save a list of last opened projects in the settings, I guess... Though the query would transparently deal with removed project folders and un/mounted volumes with projects on them. Won't work with non-BFS storage though.
> Decisions, desicions... all yours. :)

We have been tinkering with asynchronous project loading. I hope we'll manage to implement it in the next release. I think we also need a way to show background tasks and be able to stop them.
This way, if one accidentally opens a really large folder, he can stop the task, or at least, the task won't freeze the whole app.

**Comment by jackburton79** [comment]
I see also how the volume got into the recent projects list: that list is built from the recent folders, so if you opened a volume in tracker, it would end up in that list.

**Comment by jackburton79** [comment]
Worked around in 00d706a28012e475edcccce3739c7931854a4086 but not a complete fix.
At least it won't let you open a volume as a project now.

**Comment by jackburton79** [comment]
Although opening a big folder takes a lot of time, the situation is not so bad as before. I guess we can close this.
