### ISSUE TITLE
Ship templates with rdef instead of rsrc file

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#208]
Only the template "BApplication with windows and menu" comes with a Resources.rsrc file.
The other GUI app template "BApplication with window" should have one, too, I'd say. Also added in the Makefile.

Plus, using a plain text rdef file would be better than a binary rsrc.
Could also include a stand-alone "resource.rdef" file along with the other template files.

It could look like this:

```
resource app_signature "application/x-vnd.YourName-YourApp";

resource app_version {
	major  = 1,
	middle = 0,
	minor  = 0,

	variety = B_APPV_FINAL,
	internal = 0,

	short_info = "A short description",
	long_info = "A little bit longer description"
};

resource app_flags B_MULTIPLE_LAUNCH;

resource file_types message
{
	"types" = "text/plain"
};

resource vector_icon {

};
```

And add the actual icon data of a variation of Haiku's default 3-coloured-boxes to put your Genio stamp on all binaries the users create and don't bother to add a custom icon. :)

**Comment by jackburton79** [comment]
Mostly done. Still missing the nice icon.

**Comment by humdingerb** [comment]
If Zumi can't whip something amazing up on short notice, maybe just use differently coloured 3-boxes, similar to Haiku generic app icon, as mentioned...
