### ISSUE TITLE
Settings: 'General' settings not live

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#209]
All settings appear to be applied live. In the "General" section at least the two checkboxes - "Auto-collaps" and "full path in title" does not.

**Comment by humdingerb** [comment]
I just noticed, even worse, the "full path" needs a Genio restart.
Also, a checkbox labelled "Show full path" implies that when disabled the window title will show the file name without the path. But it doesn't show the file name at all, just "Genio".

Generally, maybe the window title shouldn't show "Genio" at all, and rather - to save space - show the project name and filename (with/without path). The Deskbar will still show the Genio app + icon.

And the "Auto-collapse" doesn't seem to do anything. I wonder what it's supposed to do. Automatically collapse a folder when closing the last of the files it containes?

**Comment by humdingerb** [comment]
> Generally, maybe the window title shouldn't show "Genio" at all, and rather - to save space - show the project name and filename (with/without path). The Deskbar will still show the Genio app + icon.

On second thought, there's enough space, because the Genio window is generally wide enough. And in Deskbar, the window tiles will mostly always get truncated anyway.
But adding the project name would be a good idea, so e.g. _"Genio - ProjectName : FileName.cpp_"

Sorry I'm rambling a bit...

**Comment by jackburton79** [comment]
> I just noticed, even worse, the "full path" needs a Genio restart. Also, a checkbox labelled "Show full path" implies that when disabled the window title will show the file name without the path. But it doesn't show the file name at all, just "Genio".
> 
> Generally, maybe the window title shouldn't show "Genio" at all, and rather - to save space - show the project name and filename (with/without path). The Deskbar will still show the Genio app + icon.
> 
> And the "Auto-collapse" doesn't seem to do anything. I wonder what it's supposed to do. Automatically collapse a folder when closing the last of the files it containes?

Auto collapse collapses all inactive projects and expand active projects.
I introduced it because otherwise, if you have many opened projects, they're all expanded by default and it's somewhat irritating.

I guess it should be named differently.
Anyway, both settings now are handled live.
I think I can apply it to the release branch after testing a bit more.

**Comment by jackburton79** [comment]
Adding the project name was definitely discussed, at least once. But we never got to a definitive decision :-)

**Comment by jackburton79** [comment]
After some testing, I applied the changes to the release/2 branch as well.

**Comment by humdingerb** [comment]
> Auto collapse collapses all inactive projects and expand active projects.

I see. This is only applied when opening a project or Genio itself.
FWIW, I think this sensible behaviour that doesn't even need to be optional.

> After some testing, I applied the changes to the release/2 branch as well.

I checked out the release/2 branch and did a debug-build, but the "full path" setting still isn't live. Am I missing something?

**Comment by jackburton79** [comment]
> > After some testing, I applied the changes to the release/2 branch as well.
> 
> I checked out the release/2 branch and did a debug-build, but the "full path" setting still isn't live. Am I missing something?
>
Weird. I'll recheck tomorrow but seemed tò be fixed

**Comment by humdingerb** [comment]
Never mind. It works now.
Dunno what was wrong before, but I now that I've closed the previously open projects and started from an empty Genio window it's alive...
Sorry for the noise...

**Comment by jackburton79** [comment]
Closing for now.
We'll reconsider removing the setting and improve the default setting
