### ISSUE TITLE
Haiku coding style for templates?

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#211]
Should the templates sport the Haiku coding style and MIT license headers?
It's a sensible default...

[In the future you could incorporate "haiku-format" to check/convert source files. Maybe even have the user tweak the format settings. You could choose a license for your project and have Genio insert the appropriate header, plus author info. Genio could even track what files you modified and offer to add you as author... Endless possibilities. And work for the future. :) ]

Anyway, if desired, I could PR the necessary changes. Of course, it's your call. Coding style is personal preference and if you wanna keep the template as is, that's totally fine ofc.

**Comment by jackburton79** [comment]
Yes please. We mostly use the haiku style ourselves (although not as strictly as in Haiku itself).
