### ISSUE TITLE
Menu item "Edit|Overwrite" needed?

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#216]
The shortcut for the menu item "Edit|Overwrite" is visible only as "ALT", because the B_INSERT doesn't have a symbol to show, apparently.
Is this menu needed at all? Don't all keyboards provide that key? All mine ever had, so I don't know...

**Comment by jackburton79** [comment]
I think we once had a MenuItem.cpp overridden with the code to render the menutem B_INSERT symbol (but maybe only in a branch, can't remember).
We could try to push a change in Haiku to render that symbol as well

**Comment by jackburton79** [comment]
OTOH, maybe we don't need that menu at all. I'll let @Freaxed and @nexus6-haiku comment on this one

**Comment by jackburton79** [comment]
We could just remove the menu and keep the action, for now. No impact whatsoever, I think

**Comment by nexus6-haiku** [comment]
The only downside of removing the menu would be for those who use a Mac or a Magic keyboard, maybe.

**Comment by jackburton79** [comment]
> The only downside of removing the menu would be for those who use a Mac or a Magic keyboard, maybe.
> 

Is it missing, there?
If so, it makes sense to keep it, although the menu creates a different shortcut (it's ALT+INSERT vs INSERT)

**Comment by nexus6-haiku** [comment]
Yes, missing altogether. It's simulated with some combinations of fn plus another key. I never used that mode but fn key does not work under Haiku so we'd better provide an alternative, be it a menu item or a switch in the StatusView maybe?

**Comment by nexus6-haiku** [comment]
The menu item itself would be enough to toggle the overwrite/insert mode even if ALT+INSERT or INSERT can't be used on a Mac.

**Comment by jackburton79** [comment]
> Yes, missing altogether. It's simulated with some combinations of fn plus another key. I never used that mode but fn key does not work under Haiku so we'd better provide an alternative, be it a menu item or a switch in the StatusView maybe?

On second thought, every editing or writing app in Haiku would have the same problem. I like the StatusView switch solution, though.
After all we already have the INS indicator there. Maybe It could become also a switch.

**Comment by jackburton79** [comment]
> The menu item itself would be enough to toggle the overwrite/insert mode even if ALT+INSERT or INSERT can't be used on a Mac.

Of course, but we are also "wasting" the ALT+INSERT shortcut, this way

**Comment by humdingerb** [comment]
Mac users seem to opt into harsh treatment. As John recently reported, they don't have a DEL key, now we learn no INSERT either. What's next, no TAB or ESC...? :)

Anyway, I'd find it strange to introduce a menu item for everyone just because some users have sub-par keyboards. As it's a systemwide issue, the solution should be provided by Haiku - probably via Keymap prefs - if there's enough interest for it.

Plus, the option to "overwriting" instead of "inserting" characters isn't that important. At least in my experience, I'm only aware of it when my thick fingers fumble a DEL press, which is right next to it...

**Comment by jackburton79** [comment]
Menu has been removed in the main branch
