### ISSUE TITLE
Tracker's "open with" menu doesn't work

### ISSUE THREAD

**Issue by zumikkebe** [Genio-The-Haiku-IDE/Genio#235]
Tracker's "open with" menu doesn't work if Genio is not already opened, this action only summons the app itself that opens the previous state (blank or last opened files)
Once the app is opened there are no problems, it gets the refs_receveid (I guess, I'm sorry, ain't a programmer) when the file is passed through Tracker

Tested version : 2.0.0.2

**Comment by jackburton79** [comment]
I investigated a bit: GenioApp::RefsReceived() is called before GenioApp::ReadyToRun().
The main Genio window is constructed in GenioApp::ReadyToRun(), so when GenioApp::RefsReceived() is called, the window is NULL and the function does nothing

**Comment by jackburton79** [comment]
Should be applied to release/2 branch, too
