### ISSUE TITLE
Crash after removing using an external command a project loaded in Genio 

### ISSUE THREAD

**Issue by Freaxed** [Genio-The-Haiku-IDE/Genio#240]
[Genio_debug-19778-debug-28-12-2023-11-59-19.report.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/13786211/Genio_debug-19778-debug-28-12-2023-11-59-19.report.txt)

**Comment by jackburton79** [comment]
Only happens if there are more than one project opened in Genio, it seems

**Comment by jackburton79** [comment]
Still happens sometimes
