### ISSUE TITLE
Lose program settings after reboot

### ISSUE THREAD

**Issue by oligprojects** [Genio-The-Haiku-IDE/Genio#241]
Installed version 2.0 from Haiku Depot
Load program and configure settings to suit my needs e.g. Editor style to dark
Reboot computer and lose all settings. even the setting to select editor style is now gone, and other strange behavior and errors from the options menu.
Issue seems to related to using desktop shortcut
no issue when running from command line pointing to install dir which is /boot/system/apps/Genio

**Comment by humdingerb** [comment]
Can't reproduce on Haiku hrev57431, 64bit.
No matter if I run `/system/apps/Genio/Genio` or a symbolic link to it on the Desktop.

Try doing a `message /boot/home/config/settings/Genio/Genio.settings` after changing a setting and compare when it's not saved. See what it says after a reboot, before and after starting Genio or the link on the Desktop.

**Comment by jackburton79** [comment]
Settings are saved the moment you change any of them. The only way you could lose them is if you run some older Genio versione which overwrites settings, or if you have some filesystem issue which prevents writing on disk.

**Comment by oligprojects** [comment]
youtube video https://youtu.be/Nia91KuCMtM
file system ok, no memory issues, Genio.settings look ok to me.

**Comment by Freaxed** [comment]
Thank you for posting the video!
For what I see you are not creating a desktop shortcut but you are creating
a copy of the Genio binary (I don’t see the shortcut underline under the
icon).
This explain most of the trouble when restarting from the desktop as Genio
can’t find the ‘data’ folder near the binary with alla the skins and
supported languages. Not sure about that ‘repo’ error that anyway we will
investigate.

Thanks!
Andrea

Il giorno sab 30 dic 2023 alle 17:50 Oliver ***@***.***> ha
scritto:

**Comment by oligprojects** [comment]
Thanks for the feedback Andrea. You are correct I am new to haiku and have essentially copied the binary to the desktop stand alone instead of right click -> create link -> to desktop location.
Probably wont be the last person to do it either. Might be no harm to have some check when the program runs.
Also as you said all the other weird errors I was seeing are because of the stand alone binary.

**Comment by jackburton79** [comment]
I guess we could show an alert if Genio can't find these files.
