### ISSUE TITLE
Accept a folder as argument to open as project

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#251]
It'd be nice to have Genio add a folder provided as commandline parameter as a (new) project.

Also, if Genio added folders as supported MIME type, one could right-click a folder and choose Genio from the "Open with..." menu. Which is then added as a project and made the active one.

**Comment by jackburton79** [comment]
The first part is done.

Are there other apps who register folders as a supported MIME types ?

**Comment by humdingerb** [comment]
ArmyKnife does, for example.
