### ISSUE TITLE
Not all "New" menu items available when a file is selected

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#255]
Currently, if you have a file selected in the Projects pane, you cannot select a 'file-template' (e.g. "c++ source.cpp") or "New folder" from the "New" menu. That's currently only possible if you select a folder first.

It should work whatever is selected in the Projects pane.
If a file is selected, create the new file/folder in the same folder as the selected file.
If a folder is selected, create the new file/folder in that folder (that part is working as is already).

**Comment by jackburton79** [comment]
Makes sense, I think. The reason it works this way is more an implementation limitation: some code needs to be changed in TemplateMenu and GenioWindow message handler

**Comment by jackburton79** [comment]
Implemented in #357
