### ISSUE TITLE
"Search results" tab needlessly BColumnListView

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#260]
As there's only one column "Location", a simple BOutlineListView would suffice.
I can't come up with a useful additional column that would make sorting useful...

**Comment by jackburton79** [comment]
I think it's just a case of BOutlineListView being a not-that-great class. It even had various issues when we implemented the Search results

**Comment by humdingerb** [comment]
Feel free to close.
Or find another column that'd be useful... :)
Hmm... maybe the project name the file of the search hit belongs to. It may be useful to extend the "Find in project" to "Find in all projects" (as another icon?). Then one could quickly identify where a search hit comes from.
