### ISSUE TITLE
Add comments for translators

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#269]
It turns out, that quite a few translators had issues choosing the right word for a string, esp. when used at different locations in the app. Best example is "Wrap", which means "line wrapping" in "Console I/O", but "wrap around" in the Find bar and its Settings.

B_TRANSLATED_COMMENT should be used more often. The comment should explain the meaning and if there are space constraints. The "Wrap" in the Find bar should be as short as possible, for example.

Unfortunately: https://github.com/KapiX/Polyglot/issues/74

So this would result in some re-translation. Or, if you guys have a php guru, solving the above Polyglot issue would be a major boon for all 3rd party apps...

**Comment by jackburton79** [comment]
We could start doing this on the main branch, since we will be doing major changes in the code, we might also change some strings.
Do changing translation context also force the need for retranslation?

**Comment by humdingerb** [comment]
> Do changing translation context also force the need for retranslation?

Unfortunately yes. That's what the above mentioned Polyglot issue is about.

Before pushing such a change, it's always a good idea to export all catkeys from Polyglot and tuck them away in an "old-catkeys" folder. Then one can at least manually search for a string and manually copy it over. Not ideal, of course, and getting worse the more translation you got...

**Comment by jackburton79** [comment]
At the moment the english catkeys on Polyglot are taken from the release branch. We wont upload the main branch catkeys for a while, so any new translation can go to the 2.x branch

**Comment by humdingerb** [comment]
OK. How are the branches organized? "main" is the development branch, and "release/2" is the current official release that gets bugfixes and maybe this or that feature developed in "main"?

**Comment by jackburton79** [comment]
Main is where alla development goes on. When we gets close to a major version release (2.0, 3.0, etc) we branch main into release/X.
After some time we do a release, tagging from this branch. 
From that moment on, we continue development in main, and only (with a few exceptions) apply critical bug fixes on the release branch. If critical bugs are found, we fix those in the release/X branch and release a X.1 release. If not, no more releases from that branch.

**Comment by humdingerb** [comment]
👍

**Comment by jackburton79** [comment]
> It turns out, that quite a few translators had issues choosing the right word for a string, esp. when used at different locations in the app. Best example is "Wrap", which means "line wrapping" in "Console I/O", but "wrap around" in the Find bar and its Settings.
> 
> B_TRANSLATED_COMMENT should be used more often. The comment should explain the meaning and if there are space constraints. The "Wrap" in the Find bar should be as short as possible, for example.
> 
> Unfortunately: [KapiX/Polyglot#74](https://github.com/KapiX/Polyglot/issues/74)
> 
> So this would result in some re-translation. Or, if you guys have a php guru, solving the above Polyglot issue would be a major boon for all 3rd party apps...

Since the translation contributions seem to have slowed down, and we already added some more strings, and plan to change some other, I think this could be a good moment to start doing this work.
You suggested exporting all catkeys from Polyglot and saving into an "old-catkeys" folder, before doing that.

**Comment by humdingerb** [comment]
I can work on that a bit.

> You suggested exporting all catkeys from Polyglot and saving into an "old-catkeys" folder, before doing that.

Yes. I find it's always a good idea to have a readily available source of already completed translations handy. Then we can manually update translations that haven't really changed apart from they now use B_TRANSLATE_COMMENT. I suppose those should still be marked as "Needs work" in Polyglot, in case the added comment clarified the usage and there's another word that fits better.
