### ISSUE TITLE
Add "Wrap lines" to "View" menu

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#274]
For some kind of files it can be useful to "soft-wrap" lines (at the window border ~or the vertical ruler?~).
I suppose scintilla can do that, compare to Koder.

For example, documentation HTML often has long paragraphs, which is currently quite annoying to edit because of the horizontal scrolling that's needed...

As normally source files already are "hard line-broken" at the some limit (80-100 chars), this soft-wrapping could possibly be active by default and could be applied to all open files. I.e. no individual view settings needed.

**Comment by Freaxed** [comment]
I'm ok with this and it should be straightforward to add.
I'm not convinced it should be active by default. The code column is not always so 'strong', for example on Genio we try to stay within the column with but exceeding for some chars is not a crime!

**Comment by humdingerb** [comment]
I suggest to soft-wrap at the window border, then, makes more sense anyway.
The editor view is normally quite a bit wider that the "max-column" so being a few chars over would be displayed just as before. Only if you have very narrow windows or exceedingly long lines, the soft-wrap comes into play. And normally that is what you want in this situation: see the rest of the code soft-wrapped into a new line.

There are situation where un-wrapped is better, so a togglable View menu item should be provided. Activated by default.
