### ISSUE TITLE
Avoid opening a folder (project) in case its a subfolder of an already opened project.

### ISSUE THREAD

**Issue by Freaxed** [Genio-The-Haiku-IDE/Genio#277]

**Comment by jackburton79** [comment]
Maybe we should also avoid opening a parent folder of an existing project. I guess both checks are a bit computationally-heavy, though, since we need to traverse all the subfolders and compare them to all subfolders of the project

**Comment by nexus6-haiku** [comment]
I think Std::filesystem::relative/proximate may help (and/or their lexically_ variants)

**Comment by Freaxed** [comment]
Maybe I’m wrong but isn’t as simple as a string compare? Comparing the
opening project path with the already opened projects path..


Il giorno dom 14 gen 2024 alle 22:38 Nexus6 ***@***.***> ha
scritto:

**Comment by jackburton79** [comment]
> Maybe I’m wrong but isn’t as simple as a string compare? Comparing the opening project path with the already opened projects path..

Yes, you're right.
I've committed a tentative fix in the fix/openChildFolder branch
