### ISSUE TITLE
Feature request: EditorConfig support

### ISSUE THREAD

**Issue by jmairboeck** [Genio-The-Haiku-IDE/Genio#278]
Today, there was some [discussion on IRC](https://oftc.irclog.whitequark.org/haiku/2024-01-08#1704695087-1704695291;) (mostly a "feature request" by @OscarL) to support the "Tab to spaces" setting per programming language.

[EditorConfig](https://editorconfig.org/) is a de-facto standard for this kind of configuration and even supports different configurations per directory or for specific files. E.g., `.editorcofig` can be added to a repository to have consistent settings for a project.

Many IDEs and editors support this either natively or via a plug-in (see the website).

**Comment by Freaxed** [comment]
Pre-req for this is making an haiku package for this library: https://github.com/editorconfig/editorconfig-core-c (no issue in compiling)

**Comment by Freaxed** [comment]
I saw Koder has a custom implementation for it

**Comment by nexus6-haiku** [comment]
#356
