### ISSUE TITLE
Rename "Line endings" menu items

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#294]
There's currently Unix, Dos and Mac.
Accoring to this [wiki](url[)](https://en.wikipedia.org/wiki/Newline#Representation) page, only "Classic Mac" uses CR. modern macOS uses LF.

The menu items could be more elaborate:
* LF (Haiku, Unix, macOS)
* CRLF (Windows, Dos)
* CR (Classic Mac OS)

The menu items could also be made checkmarkable to put a mark at the current file's lineending mode.

**Comment by Freaxed** [comment]
Also this topic is a bit confusing and we should fix it.
In the current implementation the line ending mode (displayed in the status bar) in derived from the file itself when the file is loaded. By changing the Line endings in the menu you are 'converting' the current document line endings to the one you choose BUT the line endings for the new lines you will then add (ugly).

We should simply set the line endings mode to the one of the file and when converting we should also change the line endings mode for the new lines.

I'm OK for the new names, much better!

**Comment by Freaxed** [comment]
Done in d43cace6513c80a390b612d69e276bc9b0c152ad
