### ISSUE TITLE
Zoom with mouse wheel

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#296]
I normally don't really use zooming the editor view. However, I imagine it could come in handy when scrolling through a long file: Zoom out, scroll around until you find what you're looking for, then Zoom back in.

If you're scrolling already with the mouse wheel, having ALT+mousewheel doing the zoom in/out would be quite covenient. Better that having to move the right hand off the mouse to do ALT +/- for the zooming.

**Comment by Freaxed** [comment]
Implemented in 0f24b7ec66fc6d130e965b59629b04dadbda8757
