### ISSUE TITLE
Reimplement the "New Project" feature with templates/stationery

### ISSUE THREAD

**Issue by nexus6-haiku** [Genio-The-Haiku-IDE/Genio#31]
We need to (re)implement the "New project" feature by using templates (as called in Paladin) or stationery (as called in BeIDE).
We may borrow some code from Paladin and adapt it to Genio with a revamped set of templates which include a .genio setting file.

**Comment by jackburton79** [comment]
Done in f474c596db6020d65b27465d25a90bcfab14c820
