### ISSUE TITLE
ConfigManager::{LoadFrom,SaveTo}File always return B_OK

### ISSUE THREAD

**Issue by lonemadmax** [Genio-The-Haiku-IDE/Genio#310]
At least since 55ebd8b.

Which means error paths, like trying ProjectFolder::_LoadOldSettings are never called. Don't know if those are unnecessary now or an overlook in ConfigManager's methods.

**Comment by Freaxed** [comment]
This PR should fix this: https://github.com/Genio-The-Haiku-IDE/Genio/pull/312

**Comment by jackburton79** [comment]
Now that I remember: LoadOldSettings() is only intended for Project settings, not for Genio settings.

**Comment by Freaxed** [comment]
To recap: with #312 we fixed the LoadFromFile/SaveToFile methods to report technical errors (files related). Unrelated to this and to the whole persistence storage change, the LoadOldSettings is not working as expected a never called due to a invalid configuration.

**Comment by Freaxed** [comment]
#312 merged
