### ISSUE TITLE
Question: How to add a language?

### ISSUE THREAD

**Issue by andreasdr** [Genio-The-Haiku-IDE/Genio#315]
Hi there,

is there a plugin system or something to add a custom new language?
I also looked in PE but did not found anything yet.

I like to add our MiniScript language or provide some configuration file for it.
- https://github.com/Mindty-Kollektiv/miniscript

Best regards
Andreas

**Comment by lonemadmax** [comment]
Have a look [languages.yaml](https://github.com/Genio-The-Haiku-IDE/Genio/blob/main/data/languages.yaml) and the files in, well, the [languages](https://github.com/Genio-The-Haiku-IDE/Genio/tree/main/data/languages) directory. You can add your own similar file and directory in ~/config/settings/Genio/ with additional languages. That is, unless none of the lexers in lexilla work for your language, in which case you'd have to implement one.
The format of the language files seems to be described in [Languages.cpp](https://github.com/Genio-The-Haiku-IDE/Genio/blob/245d0abd51d15318670709a6b860ced1afcca4b8/src/helpers/Languages.cpp#L133).
