### ISSUE TITLE
Add "Show in Project" in tab context menu

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#325]
Say you have several projects open (maybe big ones with sub-folders), and several files of them open in tabs. It'd be nice to be able to jump to and select an open file in the Project's list.
Say, I have MainWindow.cpp open and would like to open MainView.cpp of that same project.  A right-click on the MainWindow.cpp tab could offer a "Show in Project" (naming could be better...) that will scroll to and select the MainWindow.cpp file. From there it's quick to find other files around it.

Might even be a nice option in the settings to "Auto-jump to current file in Projects list" that whould do this automatically every time you switch tabs. More useful than the auto-collapse/expand setting, IMO.

**Comment by Freaxed** [comment]
This feature is on my wish  list since ever! The tricky part is to refactor the tabview component to make the context menu aware of the Editor and Project behind the clicked tab.. I already have an idea on how to do it..

**Comment by humdingerb** [comment]
Great! I think this menu could do with a shortcut, maybe ALT+Y (for sYnc), because aiming on the tab and choosing from the context menu sounds quite cumbersome. Personally, I'd try having that mentioned "auto-sync" on by default to see if it may be distracting or annoying. I imagine the syncing to be more helpful than distracting, but you never know until you use it for some time...

**Comment by Freaxed** [comment]
I created a PR for this feature, if you find some time, please provide your feeback (#327) 
Thanks!

**Comment by jackburton79** [comment]
It has been merged
