### ISSUE TITLE
Add "Go to project's bugtracker" menu (+ settings)

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#330]
It's sometimes handy to go to a project's bugtracker to check up on an issue.

The project settings could add a BTextControl to the "General" page labelled "Bugtracker:" where the users can enter the URL of there project's bugtracker. Bonus points for auto-filling it with the URL if it can be derived from the source control info. Like, if it's on github get the URL and append "/issues".

The add "Go to project's bugtracker" to the context menu in the Projects pane and the "Project" menu in the menu bar.

I wondered if a second setting for the project's website would be useful, but normally your bugtracker is on the same site and whatever you wanted on the website (PRs, commit log, releases...) is just a click or two away. So to keep menus short, just add the bugtracker menuitem.

**Comment by humdingerb** [comment]
Oh, I think the item can actually be shortened to "Go to bugtracker". That it's the currently active project's one should be obvious.

**Comment by humdingerb** [comment]
On second thought, maybe this isn't really needed after all.
In most of my project's I've put a Web+ bookmark to the project's repo and Polyglot page into the project's top folder. A simple double-click on those in the Projects pane will open those sites.
Much more flexible. I hope other users think of that super easy solution, too.
I'm feeling sad for the non-Web+ users that can't just drag and drop bookmarks... :-P

Feel free to close.

**Comment by nexus6-haiku** [comment]
> I'm feeling sad for the non-Web+ users that can't just drag and drop bookmarks... :-P

Closing it for now.
BTW, bookmarks can be opened by Falkon if you change the preferred application in FileTypes, indeed.
