### ISSUE TITLE
Tab width is extremely large

### ISSUE THREAD

**Issue by bitigchi** [Genio-The-Haiku-IDE/Genio#337]
On an averagely big screen 1080p screen, only 4~ tabs are visible, depending on the project navigator width. This is extremely low. It at least needs to be halved, so that working with an average project could be somewhat manageable.

**Comment by nexus6-haiku** [comment]
Could you post a screenshot, please?
What is the system font size?

**Comment by bitigchi** [comment]
I lowered it to 12, now better... I guess I could close it.
