### ISSUE TITLE
Cannot use with Haiku source code

### ISSUE THREAD

**Issue by bitigchi** [Genio-The-Haiku-IDE/Genio#338]
When I select the `haiku` source code folder, application hangs without restoration... It would be nice to be able to use it for Haiku development.

**Comment by nexus6-haiku** [comment]
Currently Genio loads a folder synchronously and the Haiku source may require some time. How much time passed before you gave up?
There is a tentative branch to make this process asynchronous but we need more time to polish it, until then I'd recommend loading just a subfolder and run jam on it instead of the whole tree.

**Comment by bitigchi** [comment]
Oh I see then. I waited about 5 minutes on a fairly capable i5 machine... But I can wait and still use Vim in the meantime. :)

**Comment by lonemadmax** [comment]
Also, is this with a released version or from current sources? There was an algorithmic issue with loading the 50K tags of haiku sources that would lead to a very long wait. Current main, even without the async folder loading patches, takes about half a minute to load haiku sources for me (from an SSD, surely an HDD would take quite longer).

**Comment by bitigchi** [comment]
It's a release source. That's nice to hear, I can tolerate half-a-minute or a bit longer, as long as I know that I will not hang indefinitely like it currently does.

**Comment by jackburton79** [comment]
The v2.1 release suffers a performance hit if "Show repository outline" is enabled.
Switching it off could help.

**Comment by jackburton79** [comment]
> It's a release source. That's nice to hear, I can tolerate half-a-minute or a bit longer, as long as I know that I will not hang indefinitely like it currently does.

Have you had the chance to test with a development build?

**Comment by bitigchi** [comment]
I don't have access to that particular machine at the moment, and won't have for another 8-9 months. Sorry!

**Comment by grexe** [comment]
Development build works fine with haiku src for me, performance, wise, but has another issue with includes that resolve just fine during compile, but Genio complains they cannot be found... will check and open a separate issue if not known already.

**Comment by jackburton79** [comment]
I think there are some include directories which are not visibile by default for clang, you need to tweak the clang settings. I could try in the next few days

**Comment by jackburton79** [comment]
Since Genio can now be used for haiku development, I'd close this issue

**Comment by jackburton79** [comment]
> Development build works fine with haiku src for me, performance, wise, but has another issue with includes that resolve just fine during compile, but Genio complains they cannot be found... will check and open a separate issue if not known already.

You have to tell clangd to include additional directories.
To do that, add a .clangd file in the root directory of haiku project.
For example, I added a basic one to include private/app and private/interface folders:

```

CompileFlags:
  Add: [-I/boot/system/develop/headers/private/app, -I/boot/system/develop/headers/private/interface]

 
```

I vaguely recall some commit where they put this setting file in haiku repo, but obviously it's not like this.
