### ISSUE TITLE
Outline pane updates show redraw flicker

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#345]
A small detail, sure, but kinda annoying... :)

**Comment by jackburton79** [comment]
This is weird: it doesn't seem happen always it seems.
Anyway: I tried BWindow::DisableUpdates() and locking the looper while adding / removing items in the BOutlineListView but doesn't seem to have any effect

**Comment by nexus6-haiku** [comment]
@humdingerb are you using the latest version on main?

**Comment by humdingerb** [comment]
I've updated once more and the flicker is barely visible now, sometimes when scrolling. Good enough for me...

**Comment by jackburton79** [comment]
Nice!

**Comment by jackburton79** [comment]
Happens again, noticeable

**Comment by jackburton79** [comment]
Fixed more correctly by @Freaxed work in 74e0c3205b8f613c5d61b166eb02c963a8b9c588
