### ISSUE TITLE
Outline: Simplify context menu items

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#349]
The context menu on a symbol in the outline list shows, e.g.:

* Go to "GenioWindow::MenusBeginning"
* Rename "GenioWindow::MenusBeginning"

It's needlessly specific, as the user knows what list entry they right-clicked and it's still selected in the list. Repeating the same symbol name has the user read it all once more. While it's not immediately tiring, you can't stop your brain reading the whole menu item, though probably after a while, you just concentrate on the "Go to..." or "Rename..." start and ignore the rest. So, the symbol name could be removed to begin with...

Also, the renaming of the above example is actually only the method name part, "MenuBeginning", so you're not able to actually rename the presented string.

Other menus aren't that specific, even if they could. For example in the Projects pane, it's "Open|Rename|Delete file" without quoting the file name.

The Outline context menu could be shortened to:

* Go to symbol
* Rename symbol

**Comment by jackburton79** [comment]
Yes I agree

**Comment by nexus6-haiku** [comment]
Object repetition in the context menu is also adopted by other ide (Xcode and Nova, I don't remember but maybe VSCode as well) and has a specific purpose: to make the object of the action explicit in case one selects the wrong one.
I agree that including the class name plus "::" could be avoided and stripped with a regexp.
But I don't see the difference, the action would apply to part of the symbol regardless as we are not going to rename class::symbol anyway.

**Comment by humdingerb** [comment]
> Object repetition in the context menu is also adopted by other ide (Xcode and Nova, I don't remember but maybe VSCode as well) and has a specific purpose: to make the object of the action explicit in case one selects the wrong one.

Genio is the only IDE I use, so I cannot compare it to others.
In this case, though, I think showing/repeating the symbol name is not necessary. The "Rename" function opens an alert for the actual renaming. By default, the renaming text box shows the symbol name. In #351 I added the original symbol name additionally to the label in that renaming alert. That way it's always visible while renaming.

Also, repeating the symbol name in the context menu may become even more tiring if more items are added. For example, I could imagine a "Find symbol" may be useful that would do a "Find in project" for that symbol. With that the user could see in the "Search results" where the symbol is used. (Let me know if that would be worth a new feature-issue.)
