### ISSUE TITLE
Outline: symbol renaming not project-wide

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#354]
As was explained in #353, renaming a symbol should rename it in the whole project, not just in the opened file. For example:

* open src/project/ProjectItem.h of Genio
* use "Find in project" to search for the variable "fSourceItem"
* rename the symbol "fSourceItem" to "fSourceItem123"

It got renamed in ProjectItem.h alright, but not in ProjectItem.cpp.
The "Search results" still shows "fSourceItem" and double-clicking is reveals it really wasn't renamed to "fSourceItem123".

**Comment by nexus6-haiku** [comment]
What happens if you the other way around?

**Comment by nexus6-haiku** [comment]
One more thing, is ProjectItem.cpp already opened?

**Comment by jackburton79** [comment]
Does LSP needs the compile_commands. Json db to be able to identify all the places where the symbols are present?

**Comment by humdingerb** [comment]
I should add: I use the binary of a self-compiled debug version, not an installed Genio package. Am I missing some "plug-ins" that are only available in a "regular" installed Genio package?

**Comment by nexus6-haiku** [comment]
> can only rename the symbol "fSourceItem" in the Outline pane of "ProjectItem.h".

Can't you rename it from the .cpp file?

**Comment by nexus6-haiku** [comment]
> I missing some "plug-ins" that are only available in a "regular" installed Genio package?

Genio does not support extensions atm, so no I don't think you miss anything

**Comment by humdingerb** [comment]
I can't rename "fSourceItem" in the .cpp, because it's only declared in the .h and therefore not in the Outline list of the .cpp file.

If I rename a symbol of the .cpp file's Outline list, the corresponding .h is opened, but the symbol in there - I renamed a member function - doesn't get renamed.

**Comment by nexus6-haiku** [comment]
You can rename a symbol from everywhere by clicking with the right button and choosing "Rename symbol".
If this works well either from the .h or .cpp file, and it doesn't from the outline I might have a clue.

**Comment by humdingerb** [comment]
Oh, I just discovered that... :)
But no. Renaming it in the .cpp does not rename it in the .h. It does work if the .h file is already open.

BTW, to be consistent, the context menu item in the editor view should also be "Rename symbol".
