### ISSUE TITLE
Genio settings: "Convert tabs to spaces" not working

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#363]
In Genio's editor settings, "Convert tabs to spaces" appear not to be working.
I suppose any open and newly opened files should automatically have their tabs converted to spaces.

**Comment by nexus6-haiku** [comment]
If you are on commit 8dba593 and later, these settings are skipped in favour of .editorconfig:

- trim trailing whitespace
- convert tabs to spaces
- tab width

These will be applied globally in one of these cases:

- ignore .editorconfig is enabled
- there is no valid .editorconfig
- one or more property is set to _undefine_ in .editorconfig

The .editorconfig settings are applied on a per file basis, you can check whether a file is configured with .editorconfig or via global settings by looking at the symbol in the file status bar:
![2024-04-24_23-57_1](https://github.com/Genio-The-Haiku-IDE/Genio/assets/105149392/fe1fb16d-5773-45ec-9264-47c3accd1e43)
![2024-04-24_23-57](https://github.com/Genio-The-Haiku-IDE/Genio/assets/105149392/aa4960a0-4529-4400-bf87-3d3f53d6a63c)

**Comment by nexus6-haiku** [comment]
The warning makes sense, would you be able to create a PR for this?

For the settings applied to your project without .editorconfig, could you share the project so I can have a look?

**Comment by humdingerb** [comment]
> The warning makes sense, would you be able to create a PR for this?

Possibly. If I can find out how to add a simple text without any actual setting behind it... Any hints? :)
(I suppose having that horizontal separator (BBox?) as in the mockup is out of the question?

> For the settings applied to your project without .editorconfig, could you share the project so I can have a look?

Any will do actually. For example https://github.com/humdingerb/samedi

**Comment by nexus6-haiku** [comment]
this is quite weird, editorconfig_parse() returns 0 (no error) even if there is no valid .editorconfig.
Need to investigate further.

**Comment by nexus6-haiku** [comment]
@humdingerb please confirm this fixes the issue and close accordingly.

**Comment by humdingerb** [comment]
I confirm, the status icon mixup is fixed. Thanks!
