### ISSUE TITLE
"Bindcatalogs" using wrong exe in debug mode

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#369]
If you're in debug build mode and invoke "Make bindcatalogs" the catalogs get added to the executable defined as the "Release" target, instead of the "Debug" target.
For example, for the Genio project, they are added to ./app/Genio instead of ./app/Genio_debug.

**Comment by jackburton79** [comment]
We can probably solve this for Genio (by using "make debug=1 bindcatalogs"), but I think this won't work for other projects, unless they use the same way to enable debug builds.
What do you think, @Freaxed ?

**Comment by Freaxed** [comment]
With the default Haiku makefile you can use “make DEBUGGER=TRUE
bindcatalogs” to enable debug build.

Il giorno gio 2 mag 2024 alle 23:50 Stefano Ceccherini <
***@***.***> ha scritto:

**Comment by jackburton79** [comment]
Ok, what I meant it would work only for makefile engine projects, it can't be done in a generic way. Just like we have release and debug build profiles, one could have different debug builds commands

**Comment by humdingerb** [comment]
Yeah, this catkeys business is a bit of an issue, because "bindcatalogs" and "catkeys" are makefile_engine targets. If you don't use Makefiles, both menu items don't make sense...

One could do what those targets do 'manually' and invoke "collectcatkeys" or `linkcatkeys` etc. manually. But where to configure which languages to process if it's not defined in a Makefile? You'd need a new Project setting with checkboxes for all catkeys that are found in the locales folder.

Sorry, I'm brain-storming here... :)

**Comment by jackburton79** [comment]
> Yeah, this catkeys business is a bit of an issue, because "bindcatalogs" and "catkeys" are makefile_engine targets. If you don't use Makefiles, both menu items don't make sense...

Yeah, I guess we would need to detect if the project is makefile_engine based and only enable these menuitems in that case.

> One could do what those targets do 'manually' and invoke "collectcatkeys" or `linkcatkeys` etc. manually. But where to configure which languages to process if it's not defined in a Makefile? You'd need a new Project setting with checkboxes for all catkeys that are found in the locales folder.
> 
> Sorry, I'm brain-storming here... :)

Np, it's always useful to do that :)

**Comment by jackburton79** [comment]
> make DEBUGGER=TRUE bindcatalogs

I tried the following commands (from commandline) without luck:

```
make DEBUGGER=TRUE bindcatalogs
make DEBUGGER=1 bindcatalogs
make DEBUG=TRUE bindcatalogs
make DEBUG=1 bindcatalogs
DEBUGGER=TRUE make bindcatalogs
DEBUGGER=1 make bindcatalogs
DEBUG=TRUE make bindcatalogs
DEBUG=1 make bindcatalogs

```

also with semicolon between the variable and commands.

**Comment by jackburton79** [comment]
Already fixed locally, will commit later
