### ISSUE TITLE
Copy&Paste error

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#370]
See https://github.com/Genio-The-Haiku-IDE/Genio/blob/main/src/ui/GenioWindow.cpp#L2664:

```
	ActionManager::RegisterAction(MSG_TOGGLE_SPACES_ENDINGS,
								   B_TRANSLATE("Show whitespace and line endings"),
								   B_TRANSLATE("Show whitespace"), "kIconShowPunctuation");
```

Is the last line supposed to be:
`	   B_TRANSLATE("Show whitespace and line endings"), "kIconShowPunctuation");`

I'm not quite sure where in the GUI these two strings appear.

**Comment by lonemadmax** [comment]
> I'm not quite sure where in the GUI these two strings appear.

The first one is the label for menus, the second is the tooltip for buttons. Looking for the message, I only see it added to the main window toolbar, so only the second string seems to be used now. The (view) menu uses the previous two distinct actions.

**Comment by Freaxed** [comment]
> The first one is the label for menus, the second is the tooltip for buttons. Looking for the message, I only see it added to the main window toolbar, so only the second string seems to be used now. The (view) menu uses the previous two distinct actions.

Exactly! The first string is not currently used (and maybe never will) this because in the toolbar we have a single button to perform two actions: show whitespace and line endings while on the menu the two actions are split in two different items.

Hope this helps

**Comment by humdingerb** [comment]
Alright. Feel free to close. Though, for consistency's sake and potential future usage, the two strings under `MSG_TOGGLE_SPACES_ENDINGS` should probably be the same, and not one of them identical to `MSG_WHITE_SPACES_TOGGLE`.

**Comment by jackburton79** [comment]
Fixed
