### ISSUE TITLE
Makefile project not recognized in debug build mode

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#378]
As briefly mention at https://github.com/Genio-The-Haiku-IDE/Genio/pull/367#issuecomment-2080470952 , Genio reconizes Makefile projects and is able to build them without special configuration by the user.

It does work, but only in Release Build Mode. If you set the Build Mode to "Debug", however, the please-go-configure-alert pops up.

**Comment by jackburton79** [comment]
I started working on improving the detection process in a branch.
Currently it has various regressions, but I hope to work on it soon

**Comment by jackburton79** [comment]
Fixed with #368
