### ISSUE TITLE
Current cursor position (line) changes in background opened files with no reason

### ISSUE THREAD

**Issue by nexus6-haiku** [Genio-The-Haiku-IDE/Genio#4]
It seems that sometimes when you switch from file A to file B in the editor, change the line where the cursor is in file B then go back to file A, the current line in A changed with no apparent reason.
Further investigation is required.

**Comment by Freaxed** [comment]
This is what I've noticed:
File A and B opened. Active tab on file A, caret at a line N, you scroll down or up without moving the caret but in a position where the caret is no more visible. Switch to tab B. Switch back to tab A. The editor automatically scroll back to the caret position at line N.
Non sure if this is the correct behaviour. I would prefer the editor not to scroll automatically.

**Comment by nexus6-haiku** [comment]
I was under the impression that this happened also when the caret is moved but I may be wrong. However, I agree with you

**Comment by Freaxed** [comment]
I wish we could fix behavior, or at least make it configurable.

**Comment by Freaxed** [comment]
Not really. The save caret option stores the cursor position inside the
file attribute.
The problem here is to avoid an 'autoscroll' when you jump from one file to
another. Genio autoscolls to the caret position, no matter if you are
viewing another section of the file.
This behaviour looks wrong to me.

Il giorno ven 27 ott 2023 alle ore 14:39 Stefano Ceccherini <
***@***.***> ha scritto:

**Comment by Freaxed** [comment]
this is the code autoscrolling (with some comments from the Ideam author):

```
				// In multifile open not-focused files place scroll just after
				// caret line when reselected. Ensure visibility.
				// TODO caret policy
				editor->EnsureVisiblePolicy();
```
Found on GenioWindow.cpp around line 1069.

If you all agree, I can remove it.

**Comment by nexus6-haiku** [comment]
Please go ahead!

**Comment by Freaxed** [comment]
Fixed in https://github.com/Genio-The-Haiku-IDE/Genio/commit/472c6b8a12ce247d89590d915f66134314ebf07f
