### ISSUE TITLE
Add a way to update Outline pane

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#407]
In case you delete e.g. a function, its symbol is still visible in the Outline pane.
It needs a way to get updated, best without user interaction like an update button. If it's not possible to know when an update is necessary, maybe doing it at least when saving a file could be good enough?

**Comment by jackburton79** [comment]
The Outline should update automatically:  after any change to the file LSP sends symbols update and the outline updates accordingly.
If that doesn't work it's a bug.
Have you got a specific test case ?

**Comment by humdingerb** [comment]
I just tried again, and now it works!

Yesterday, I have removed a complete function implementation from a .cpp file, because I moved it to another file. I selected the whole thing, pressed DEL. The function gone in the editor view, the symbol (`CheckView::ShowPopUpCalendar`) was still in the Output pane.

Anyway, no idea what was different then, but it does work now. Sorry for the noise...

**Comment by jackburton79** [comment]
I guess you are current ?

**Comment by jackburton79** [comment]
Let's close this, then.
