### ISSUE TITLE
crash when opening file in a new project generated from a template

### ISSUE THREAD

**Issue by grexe** [Genio-The-Haiku-IDE/Genio#409]
Just had Genio crash when opening an existing project from my local git repo and then generating another project from the "BApp with window" template and opening a src code file there. Sadly could not reproduce, but maybe the attached debug report helps.
Using the newly released 2.1 version.

**Comment by grexe** [comment]
[Genio-5707-debug-13-06-2024-16-38-50.report.txt](https://github.com/user-attachments/files/15825752/Genio-5707-debug-13-06-2024-16-38-50.report.txt)

**Comment by jackburton79** [comment]
This one might have been fixed in main, already.

**Comment by jackburton79** [comment]
I just checked, and it has been fixed with cf4566579ac788133946303a6ef8296303b70a0f , indeed.
