### ISSUE TITLE
Makefile from App template does not work

### ISSUE THREAD

**Issue by grexe** [Genio-The-Haiku-IDE/Genio#410]
(using Genio dev build as of today)

When creating an App from the App template, the following stanza is included in the generated Makefile:

```
## Include the Makefile-Engine
#DEVEL_DIRECTORY := \
#	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
#include $(DEVEL_DIRECTORY)/etc/makefile-engine
```

> Error: Failed to find path: No such file or directory
> Makefile:125: /etc/makefile-engine: No such file or directory
> make: *** No rule to make target '/etc/makefile-engine'.  Stop.

This does not work and yields the following error message on Haiku hrev57755:

Instead, this one I cobbled together myself from the official Haiku examples and sources works (look closely - same same but different...):
```
## Include the Makefile-Engine
DEVEL_DIRECTORY = \
	$(shell findpaths -e B_FIND_PATH_DEVELOP_DIRECTORY etc/makefile-engine)
include $(DEVEL_DIRECTORY)
```

**Comment by jackburton79** [comment]
Which template ? I just tried "Console application" and "App with Window" but they built correctly.
On which platform, by the way ?

**Comment by jackburton79** [comment]
I meant

> Which template ? I just tried "Console application" and "App with Window" but they built correctly. On which platform, by the way ?

I meant: x64 or 32bit ?

**Comment by grexe** [comment]
I'm on x86_64

**Comment by jackburton79** [comment]
Which template did you try which has this problem ?

**Comment by grexe** [comment]
App with Window.

**Comment by nexus6-haiku** [comment]
That makefile is exactly the same template used by the Tracker, btw.
Could you check if that works?

**Comment by jackburton79** [comment]
Sorry, cannot reproduce either on haiku beta4 and master, both 32 bit and 64 bit.

**Comment by jackburton79** [comment]
Please reopen if you can provide a reproducible test case
