### ISSUE TITLE
Build mode is not saved

### ISSUE THREAD

**Issue by jackburton79** [Genio-The-Haiku-IDE/Genio#43]
Project build mode is not saved, unless you open the project settings and click on "save".
Given that the project build mode is in a menu and not in the project settings window, this is unintuitive.

**Comment by nexus6-haiku** [comment]
When a folder is loaded and it does not have a project configuration file, build menu should be disabled at all.
Another option is to keep it enabled but every item if selected should show an alert warning the user that the operation is not permitted until the project is setup and it should ask to open the config window.
I think the second looks more intuitive.
