### ISSUE TITLE
Regression: changing active project doesn't redraw projects pane

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#433]
This works in the current release version, but not when building current head.

* Open a few projects
* Select a currently non-active project in the Projects pane
* "Set active" the selected project

-> Nothing seems to change. The old active project is still bold, the newly activated project isn't bolded.
You have to force a redraw, e.g. by waving a window in front.

I suspect the recent changes to allow dropping folders as new projects has messed up some Invalidate() or something?

**Comment by jackburton79** [comment]
I guess I broke this with my recent commits.

**Comment by jackburton79** [comment]
Weirdly I definitely reproduced it once or twice but can't reproduce this anymore.
There's definitely some missing updates in certain cases, though

**Comment by humdingerb** [comment]
Weird. 100% reproducible here. Load 3 projects. Collapse all. Make the 1st active. Select the 3rd and make it active. The 1st stays bold. If you select the 2nd one in the middle, both 1st and 3rd are bolded.

**Comment by jackburton79** [comment]
Ok, I managed to reproduce it more or less consistently. There's something strange:
It seems like invalidating the ProjectBrowser doesn't invalidate correctly the BOutlineListView, which is a child.
I tried to Invalidate it explicitly like this, and it seems to fix the problem. Obviously it's not a real fix.
https://github.com/Genio-The-Haiku-IDE/Genio/tree/experimental/fixInvalidate

@Freaxed, @nexus6-haiku any idea why the invalidation isn't passed to the child view ?

**Comment by jackburton79** [comment]
The workaround fixes also the other drawing glitch : the build indicator remains on screen until you force a redraw

**Comment by jackburton79** [comment]
I added a workaround in main. Please test and see if it fixes the problem also for you

**Comment by humdingerb** [comment]
Yep. Completely fixed!

**Comment by jackburton79** [comment]
Fixed, although IMHO it's a workaround.

Since I don't know if it's a bug or a misinterpretation, I did a post in the Haiku forums here https://discuss.haiku-os.org/t/redrawing-invalidation-clarifications/15656 asking for clarifications
