### ISSUE TITLE
latest build (as of 7. Oct. 2024) has make issues and crashes on startup

### ISSUE THREAD

**Issue by grexe** [Genio-The-Haiku-IDE/Genio#435]
(merging these two issues since it's not a release issue and seems to be related)

I cannot build the latest Genio sources with `make deps && make` for days now, getting a dependency error:
`make: *** No rule to make target 'src/override/BarberPole.h', needed by 'objects.x86_64-cc13-release/RemoteProjectWindow.o'.  Stop.`

When I `BUILD_WITH_CLANG` (using clang 18.1.7), the build goes through, but the toolbar icons are missing and this crashes Genio (should fall back to text or default icons in that case, really), see attached report.
[Genio-1676-debug-07-10-2024-11-07-42.report.txt](https://github.com/user-attachments/files/17277502/Genio-1676-debug-07-10-2024-11-07-42.report.txt)

**Comment by jackburton79** [comment]
We removed Barberpole since it's now included in beta5. Deleting BarberPole.d should do the trick.
As for the other issue, I noticed it too. I had to do a round of fixes for clang which were not needed previously. Moreover, I remember clang build working some time ago. I guess something has changed with newer clang.

**Comment by jackburton79** [comment]
Did deleting BarberPole.d work ?

**Comment by jackburton79** [comment]
I removed the debugger() call which would get triggered if the Outline icons are missing, but the problem with clang build is that resources are not built correctly inside the executable, nothing we could fix in Genio right now.

**Comment by grexe** [comment]
I could swear I tried a ´make clean´ before reporting this, but after another cleanup (including manually removing all object* folders) it worked:)
Don't worry about clang, it's not that important right now, better focus on the IDE itself:^)
