### ISSUE TITLE
Package Genio to sit directly in /system/apps/

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#436]
Many devs use the Terminal for lots of stuff. It would be nice if Genio sat in the usual PATH instead of a /system/apps/Genio/ subfolder.

The data etc. would then have to move into the $dataDir.

**Comment by jackburton79** [comment]
Will do

**Comment by jackburton79** [comment]
Would $dataDir be /boot/system/data/Genio in our case ?

**Comment by jackburton79** [comment]
Done. I also updated the recipe but will work for the next release.
We would release a 3.1 but I wanted to fix also #428 . I have no idea what's wrong, though so we could end up doing a 3.1 without that fix.
