### ISSUE TITLE
Accept folder as parameter from CLI

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#441]
Shame you guys were so fast with the v3.1 release... this would've fitted in with Genio moving into PATH. :)

In Terminal, if you added a folder (often probably "." for the current one) as parameter, it'd be nice if Genio opened with that project loaded and active.

**Comment by jackburton79** [comment]
Do you think Genio should still open the "saved" projects in that case, like we do when we pass a file to the commandline?

**Comment by humdingerb** [comment]
I think so, yes.
The question is, do we expect to also have all the files open from when we last quit Genio?
Invoking Genio with a folder==project from the commandline may suggest the user wants a clean slate.

**Comment by humdingerb** [comment]
OTOH, "Close all tabs" is quickly done. Your call :)

**Comment by jackburton79** [comment]
> I think so, yes.
> The question is, do we expect to also have all the files open from when we last quit Genio?
> Invoking Genio with a folder==project from the commandline may suggest the user wants a clean slate.

Yeah, especially because using the commandline is a quite specific action

**Comment by jackburton79** [comment]
It's done (very basically) in 3bd065c7b458d74f0e495438ca85be6c5daed54f .
It's not made active yet, though.
This has the bad consequence that dropping a folder into the window (and not only into the project browser) will also open it as a project now.
I guess we can change that.
