### ISSUE TITLE
Add option for small toolbar icons

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#446]
The Genio settings should provide a setting in General|Appearance for small toolbar icons. For people that want to maximize usable screen space, but still want to use toolbar icons, so they don't hide the toolbar altogether.

What's needed? Just a "Small toolbar icons" checkbox or an all out size slider with live-changing main window (if that's possible)?

In any case, the icon size should be font size dependent, i.e. use `be_control_look->ComposeIconSize()` and scle from there.

**Comment by jackburton79** [comment]
Yes, I agree

**Comment by jackburton79** [comment]
> The Genio settings should provide a setting in General|Appearance for small toolbar icons. For people that want to maximize usable screen space, but still want to use toolbar icons, so they don't hide the toolbar altogether.
> 
> What's needed? Just a "Small toolbar icons" checkbox or an all out size slider with live-changing main window (if that's possible)?

I've added an option to have smaller icons for now.

> In any case, the icon size should be font size dependent, i.e. use `be_control_look->ComposeIconSize()` and scle from there.

Any example of how to scale correctly ?

**Comment by jackburton79** [comment]
Nevermind, I found out.

**Comment by humdingerb** [comment]
OK. The current small icons appear to be smaller than necessary, or the buttons are bigger than needed for the icon size. :)

**Comment by jackburton79** [comment]
> OK. The current small icons appear to be smaller than necessary, or the buttons are bigger than needed for the icon size. :)

Which buttons you mean? 
I used ComposeIconSize with 16 as parameter for small icons and 32 for big icons.

**Comment by humdingerb** [comment]
All icons, e.g. the toolbar. There just seems to be more padding around the icons than needed.
Compare Pe's vs. Genio's toolbar icons:

![toolbar](https://github.com/user-attachments/assets/03e2e680-48e4-44e2-9e6e-9bde22f1493a)

I guess the icon size is correct, but the padding of icons in BButton's SetIcon() or whatever is a bit generous...

**Comment by jackburton79** [comment]
Oh I see. Could be that. Looking into it

**Comment by jackburton79** [comment]
Actually, there is no way to change padding. Maybe our icon are just smaller (meaning they occupy a smaller part of the button). I compared with Koder (which uses the same toolbar code) and the padding is the same. I incremented the small icon size to 20, anyway, since they look a bit better this way.
