### ISSUE TITLE
No potential fix available at called object type 'bool' is not function or function pointer

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [Genio-The-Haiku-IDE/Genio#447]
![image](https://github.com/user-attachments/assets/8d5a50cc-3523-4783-9e94-1550e712b5fb)
When I add bool to start at isScanning(true); issue fixes himself

**Comment by jackburton79** [comment]
Not sure I understand the issue : the code is certainly wrong, the issue is that Genio doesnt suggest the correct fix?

**Comment by HydraDragonAntivirus** [comment]
> Not sure I understand the issue : the code is certainly wrong, the issue is that Genio doesnt suggest the correct fix?

yeh, it didn't suggested bool thing. Also, code is currently template, sorry for that.

**Comment by HydraDragonAntivirus** [comment]
I also realized this also happens when you forgot close include like you forgot this ">"

**Comment by jackburton79** [comment]
> > Not sure I understand the issue : the code is certainly wrong, the issue is that Genio doesnt suggest the correct fix?
> 
> yeh, it didn't suggested bool thing. Also, code is currently template, sorry for that.

I don't mean wrong as in bad, just not formally correct (hence the warnings). 

Anyway: we rely on what clang suggests as fixes, so there is not much we can do here.
