### ISSUE TITLE
Build menu item is disabled after building several times a project.

### ISSUE THREAD

**Issue by nexus6-haiku** [Genio-The-Haiku-IDE/Genio#59]
This usually happens when a series of subsequent builds is performed by using the keyboard shortcut. After a while the build menu item gets disabled. Activating a different project in the workspace e reactivating the previous one usually fixes the problem.
Maybe related to this, sometimes it happens when the build task is not completed correctly (i.e. "--------------------------------   build ended   ----------------------------------" does not appear)

**Comment by jackburton79** [comment]
A tentative fix has been done with the better-console-io branch, now merged in main.

**Comment by jackburton79** [comment]
Unfortunately it seems there are still problems. Sometimes build doesn't terminate.
If I stop it manually (hitting "Stop"), at the next build Genio crashes.

**Comment by Freaxed** [comment]
Any stacktrace?

Il giorno lun 29 mag 2023 alle 15:39 Stefano Ceccherini <
***@***.***> ha scritto:

**Comment by jackburton79** [comment]
Does still happen for any of you ?

**Comment by jackburton79** [comment]
I've tried hard to reproduce this problem, but haven't seen it in a while.

**Comment by jackburton79** [comment]
Seems gone. We can reopen if someone encounters this again.
