### ISSUE TITLE
Tab close button position should be reversed

### ISSUE THREAD

**Issue by bitigchi** [Genio-The-Haiku-IDE/Genio#67]
Just like macOS, the tab close button position should match the system window tab close button position. It should be left aligned, instead of right. File names can be centre-aligned.

**Comment by Brunobasta** [comment]
why?

**Comment by jackburton79** [comment]
> Just like macOS, the tab close button position should match the system window tab close button position. It should be left aligned, instead of right. File names can be centre-aligned.

I somehow recalled WebPositive had the tab close button on the right side, but it doesn't have any.
Anyway, personally I don't have a strong opinion on this, but I don't think the tab close position should necessarily match the system window close button position.

**Comment by jackburton79** [comment]
Let's close this for now. We'll see how It works out.
