### ISSUE TITLE
Provide option to build with gcc11 on 32bit

### ISSUE THREAD

**Issue by Begasus** [Genio-The-Haiku-IDE/Genio#69]
Some sources `can't be build with gcc2` anymore, and for now Genio can only use the `primary compiler (gcc2)` for creating and building projects.
In Terminal on 32bit we can switch compiler with `setarch x86` for this, would be nice to see Genio being able to use the `secondary architecture compiler (gcc11)` also.

**Comment by nexus6-haiku** [comment]
Although you can't really select the target on the fly while you build, you can input something like:

setarch x86; make

in the build command fields. If you need to switch between archs then you should change the settings every time.
We acknowledge this is a limitation that should be addressed.

As a side note, you can input whatever you want in the command fields: a single command, multiple commands seprated by ";" or even a custom script. All the path can be expressed as absolute or relative the current project root folder.

**Comment by Begasus** [comment]
Adding `setarch x86; make` in `Release build command:` doesn't seem to do anything other then mention `build started` and `Switching to architecture x86` in the tab `Build log`?

**Comment by nexus6-haiku** [comment]
I don't own a 32bit installation to test but what do you get if you give that very same command sequence via Terminal?

Could you please try things like `echo "Hello, world!"; make` or `pwd; make`?

**Comment by Begasus** [comment]
echo `Hello, world!; make` works (checked earlier with `make; make clean` that was ok too), for setarch x86 it just sits there after the mention `Switching to ...`

**Comment by nexus6-haiku** [comment]
please remove the semi-colon

`setarch x86_64 make`

**Comment by Begasus** [comment]
Thanks! Maybe this could be documented somewhere? Successfully build ArmyKnife (which can't be build with gcc2) now 👍

**Comment by nexus6-haiku** [comment]
Yes we could add it to the readme. Thanks for spotting this issue!

**Comment by jackburton79** [comment]
Tracked on #71
