### ISSUE TITLE
Add toolbar item for "Clean project"

### ISSUE THREAD

**Issue by Begasus** [Genio-The-Haiku-IDE/Genio#70]
There is already an item for `Build project`, but could use one also for `Clean project` (that's `missing a keyboard shortcut` in the menu too) in the toolbar.

**Comment by jackburton79** [comment]
The menus and toolbar are still very work in progress, we will try to improve them in the next release. I think a button and / or shortcut for make clean (or full rebuild) will probably be included

**Comment by jackburton79** [comment]
Done in 30e4a778ef7c6fc818ff038f127fa5b4cba31ffa
