### ISSUE TITLE
File type for it.catkeys is wrong

### ISSUE THREAD

**Issue by Begasus** [Genio-The-Haiku-IDE/Genio#72]
Double click en.catkeys opens the file in CatKeysEditor, opening the it.catkeys opens in Pe (or default editor).
Looking in FileTypes I see "locale/x-vnd.Be.locale-catalog.plaintext" for en.catkeys and "text/plain" for it.catkeys.

**Comment by Begasus** [comment]
Also getting an error trying to build the bindcatalogs: 
```
for lc in en it; do linkcatkeys -o app/Genio -s "application/x-vnd.Genio" -tr -l $lc locales/$lc.catkeys; done
couldn't load source-catalog locales/it.catkeys - error: Bad data
/boot/system/develop/etc/makefile-engine:386: recipe for target 'bindcatalogs' failed
```

**Comment by jackburton79** [comment]
I'd say drop this file. We uploaded the updated catkeys on polyglot.
