### ISSUE TITLE
Move some menu items

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#74]
Some menu items in the Edit menu don't actually change the code and therefore isn't 'editing' but only change the appearance and should move to the View menu:
* Fold/Unfold all
* Toggle white spaces
* Toggle line endings
* Switch source / header
* Signature help (<- not sure here. What's this?)

These items fit better in the Search menu:
* Go to definition
* Go to  declaration
* Go to implementation

As the Window menu is quite short, maybe these items of the View menu could move there, if View becomes to crowded:
* Zoom in
* Zoom out
* Zoom reset

**Comment by jackburton79** [comment]
Done most things.
I haven't moved View under Window yet, we'll see how it works

**Comment by humdingerb** [comment]
Just to clarify, I didn't mean to move the whole "View" menu to the "Window" menu, but it's zoomy items.

**Comment by jackburton79** [comment]
The zoom items only apply to the editor, so I'm not even sure they should go into Window... Or stay in View, after all.

**Comment by jackburton79** [comment]
Let's close this as we did most of the things.
There are always different views on menu hierarchy but what we have now is good enough

**Comment by jackburton79** [comment]
I think we were going to remove it also because it wasnt synchronized with the ins key, then @Freaxed fixed it so we opted to leave it there 😅
