### ISSUE TITLE
Change "Go to line..." shortcut

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#75]
Just because it's in muscle memory already, consider to use "ALT+," for the "Go to line..." shortcut.

Normally "ALT+", is triggering the settings panel of an app, but I imagine an IDE needs to sve all the shortcuts it can for often used features, and the settings are probably not changed that often...

**Comment by jackburton79** [comment]
If I remember correctly, ALT+ is currently used to zoom the editor.

**Comment by humdingerb** [comment]
The suggestion is "ALT + ,": "ALT and comma". :)

**Comment by humdingerb** [comment]
Yes. And Koder, so probably the two most-used GUI code editors.
