### ISSUE TITLE
Add catkeys to Polyglot for translation

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#78]
Once you think most existing strings don't change too much, the catkeys should be uploaded to [Polyglot](https://i18n.kacperkasper.pl/projects). One or more of the devs should get the "developer" permissions there to be able to upload catkeys. Let me know the nickname(s) at Polyglot and I take care of that.

**Comment by nexus6-haiku** [comment]
Yes, please nexus6-haiku.
Thank you!

**Comment by humdingerb** [comment]
Done. If you have questions, see the [Polyglot help pages](https://i18n.kacperkasper.pl/help) or ask me.

Not really related, but there's no Italian [Glossary](https://i18n.kacperkasper.pl/glossaries) yet. Maybe you'd like to fill in the most common terms, then people can run the "Pre-translate" first to get all those out of the way. See the other languages glossaries for hints what terms are useful to have.

**Comment by jackburton79** [comment]
Jackburton79 here

**Comment by humdingerb** [comment]
Same permissions for @jackburton79. :)

BTW, in my string-tweaking-PR I forgot to re-generate the en.catkeys...
Before uploading them to Polyglot, do't forget to do that first.

**Comment by jackburton79** [comment]
I added the project on Polyglot and uploaded the catkeys.
We should really start populating the italian glossary, too.
