### ISSUE TITLE
Smaller 2D icons for tool bar

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#79]
There's currently a mix of 2D and 3D icons in the tool bar. 2D icons are preferrable IMO, because they are better distinguishable at smaller sizes. The current icon size is a bit on the larger size...
Maybe 24px would be better; wastes less space.

There are quite a few 2D icons by zuMi, see https://haikuarchives.github.io/ZumisIcons/myhaiku/btoolbar/index.html

**Comment by jackburton79** [comment]
Zumi is working on new icons. Stay tuned.

**Comment by jackburton79** [comment]
Replaced most icons with new shiny 2d icons, made by Zumi.

**Comment by humdingerb** [comment]
Very nice! The one icon that migt be improved is the "Fold/Unfold all", I think. How about a paper plane, or possibly just a piece of paper folded like a "M". Hmmm, that would probably only work with a 3D icon. :)
Maybe a hand held fan like:
![p_white-paper-hand-fans-01](https://github.com/Genio-The-Haiku-IDE/Genio/assets/6107158/2524fb2b-42cb-4875-b08b-2761af76bfea)

**Comment by jackburton79** [comment]
We're still a bit unsure about that One. ZuMi created nice icons but there should be two states icons, since it's not easy to convey both the fold and unfold concept with just one icon. Unfortunately the toolbar api doesn't allow this.

**Comment by humdingerb** [comment]
It could be a toggle icon-button like the show/hide panel buttons. Pressed all gets folded, un-pressed all gets unfolded. I suppose if you fold-all with the button and then manually un-fold everything, once the last block is un-folded, the button has to become 'un-pressed'. (And vice-versa for folding.)

**Comment by jackburton79** [comment]
Done
