### ISSUE TITLE
Improve translations

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#85]
While working on the German translation, I had toconsult the code and saw a few things that coul be improved.

For example, alert texts often get divided into several translated strings:

```
	text << B_TRANSLATE("File \"%file%\" was moved externally.")
		 << "\n"
		 << B_TRANSLATE("Do you want to ignore, close or reload it?");
```

In the catkeys and Polyglot, these lines do not necessarily appear to next to each other. The translator won't know what the "it" in the second block refers to.

---

Other constructions are a bit awkward, e.g.:

```
BString notification;
notification << "\"" << text << "\""
	<< " "
	<< B_TRANSLATE("occurrences found:")
	<< " " << count;
```

Will result in, e.g.:

> "ShowLog" occurences found: 3

Better would be:

> "ShowLog" found 3 times

And it could respect correct pluralization.

---

I can work on that, but there are quite a lot of translatable string so it may take a bit...
If you agree, I suggest to upload a dummy en.catkeys at Polyglot for now, so people don't star working on soon to be replaced strings. The Spanish has progressed nicely already...

Maybe "Don't start translating yet, we're tweaking the strings. Started translations will be backed up and the still valid parts restored."
Do download the started translations before changing to those temporary en.catkeys...

**Comment by humdingerb** [comment]
Hmmm, I also wonder if all the strings fed to _SendNotification() ought to be translatable at all. They don't seem to appear in the GUI and are only logged somewhere. I guess it could be useful to attach the log to a bug report, but would it help you if it were localized to Chinese? :)

**Comment by Freaxed** [comment]
I agree, _SendNotification once had a GUI part now removed. We should
remove the translation macros.
Thanks!

Il giorno sab 27 mag 2023 alle 10:36 humdinger ***@***.***>
ha scritto:

**Comment by jackburton79** [comment]
We gladly accept your help for improving translations. Thanks!
A question, since I don't know how Polyglot works: what happens if we fix the translation strings and upload a fixed catkeys? Do previous translations get wiped out?

**Comment by humdingerb** [comment]
> I agree, _SendNotification once had a GUI part now removed. We should
remove the translation macros.

OK, so keep _SendNotification() in case it'll do more than write to the log in the future, but remove the macros. I'll create a PR for that.

> A question, since I don't know how Polyglot works: what happens if we fix the translation strings and upload a fixed catkeys? Do previous translations get wiped out?

Only the strings that haven't changed are kept, anything else - e.g. when you just fix a typo in one word of a string - needs to be translated once more. See also the [Polyglot help](https://i18n.kacperkasper.pl/help/developer#overview).

**Comment by jackburton79** [comment]
The PR has been merged. We just need to regenerate and upload catkeys.

**Comment by humdingerb** [comment]
The PR included en and it catkeys.

**Comment by jackburton79** [comment]
I'm going to reupload catkeys.
I've already backed up the current catkeys in Polyglot.
Do you think I can just upload the new ?

**Comment by humdingerb** [comment]
Yes, unchanged translations are kept.

**Comment by jackburton79** [comment]
Weird, this is what happens when I upload the new catkeys:
Catkeys uploaded. 238 added, 0 deleted, 0 updated (order, casing, whitespace changes), with 0 related translations marked as incomplete.

**Comment by jackburton79** [comment]
Ok I think I did something wrong:
I accidentally added two more modules with the same name
![image](https://github.com/Genio-The-Haiku-IDE/Genio/assets/3501519/0c062d79-961a-4ff9-b304-3244718dcbf8)

**Comment by humdingerb** [comment]
Oops. :)
I think we'll have to ask KapiX to remove those for us...

You'll have to click on the "Edit" link to the right of the first "Application" module and upload the new en.catkeys there.

**Comment by jackburton79** [comment]
Ah ok I see. Sorry for that

**Comment by humdingerb** [comment]
Oops again. I mailed KapiX as well... :)

**Comment by jackburton79** [comment]
I'm closing this, since it's sorted now. Thanks for your help!

**Comment by humdingerb** [comment]
👍
