### ISSUE TITLE
Genio UI does not scale properly

### ISSUE THREAD

**Issue by nexus6-haiku** [Genio-The-Haiku-IDE/Genio#94]
The ProjectBrowser scales up well up until a font size of 25, after that the icons are not rendered anymore and replaced by the default icon which is in some cases misplaced.
Moreover, the arrows used in the StatusView (right below the Editor) and in the TabManager need to scale in both directions, currently they do just vertically.
![photo_2023-05-29_15-48-42](https://github.com/Genio-The-Haiku-IDE/Genio/assets/105149392/6ad28644-1cf7-49c7-b43f-8cb5c420394d)

**Comment by jackburton79** [comment]
In the [experimental/fix-ui-scaling](https://github.com/Genio-The-Haiku-IDE/Genio/tree/experimental/fix-ui-scaling) I'm trying to fix these issues.
I've fixed the Editor statusview arrow scaling for now

**Comment by jackburton79** [comment]
Also the setting window doesn't scale correctly.

**Comment by jackburton79** [comment]
![screenshot1](https://github.com/Genio-The-Haiku-IDE/Genio/assets/3501519/399be21b-1094-4d6f-b5fa-5df9e808ee46)

**Comment by jackburton79** [comment]
Closing this since we've resolved most of the problems.
If the arrows size is really an issue, let's open another ticket.
